name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*
env:
  IMAGE_NAME: meadstats-frontend

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image
